#!/usr/bin/with-contenv bash

DATA_DIR=/config/data/
#LOGS_DIR=/config/logs/
#PLUGINS_DIR=/config/plugins/

#mkdir -p $DATA_DIR $LOGS_DIR $PLUGINS_DIR
mkdir -p $DATA_DIR

export CRONICLE_foreground=1
export CRONICLE_Storage__Filesystem__base_dir=$DATA_DIR
#export CRONICLE_log_dir=$LOGS_DIR
export CRONICLE_echo=${CRONICLE_echo:-1}

if [ ! "$(ls -A $DATA_DIR)" ]; then
    echo "$(date -I'seconds') INFO $DATA_DIR is empty, running setup ..."
    /app/bin/control.sh  setup
    echo "$(date -I'seconds') INFO done"
fi

chown abc:abc -R /app /config

printf "$DATA_DIR" > /var/run/s6/container_environment/CRONICLE_Storage__Filesystem__base_dir
