#!/usr/bin/with-contenv bash

HOME_DIR=/opt/cronicle/
BIN_DIR=/opt/cronicle/bin/
DATA_DIR=/opt/cronicle/data/
LOGS_DIR=/opt/cronicle/logs/
QUEUE_DIR=/opt/cronicle/queue/

mkdir -p $DATA_DIR $LOGS_DIR

export CRONICLE_foreground=1
export CRONICLE_Storage__Filesystem__base_dir=$DATA_DIR
export CRONICLE_log_dir=$LOGS_DIR
export CRONICLE_echo=${CRONICLE_echo:-1}
#export CRONICLE_pid_file=$HOME_DIR/cronicle.pid

if [ ! "$(ls -A $DATA_DIR)" ]; then
    echo "$(date -I'seconds') INFO $DATA_DIR is empty, running setup ..."
    ${BIN_DIR}/control.sh setup
    echo "$(date -I'seconds') INFO done"
fi

chown abc:abc -R ${DATA_DIR}
chown abc:abc -R ${LOGS_DIR}
chown abc:abc -R ${QUEUE_DIR}

unset IFS; for var in ${!CRONICLE_*}; do printf '%s' "${!var}" > "/var/run/s6/container_environment/$var"; done

if [ -n "$DOCKER_HOST" ]; then

  export DOCKER_CONFIG=${DOCKER_CONFIG:-/app/.docker/}
  
  printf '%s' "${DOCKER_HOST}" > "/var/run/s6/container_environment/DOCKER_HOST";
  printf '%s' "${DOCKER_CONFIG}" > "/var/run/s6/container_environment/DOCKER_CONFIG";
fi
